---
layout: issue
title: "Zend_Controller_Front::dispatch() does not render Zend_Controller_Response's exceptions."
id: ZF-1281
---

ZF-1281: Zend\_Controller\_Front::dispatch() does not render Zend\_Controller\_Response's exceptions.
-----------------------------------------------------------------------------------------------------

 Issue Type: Bug Created: 2007-04-16T14:59:11.000+0000 Last Updated: 2007-07-05T14:44:05.000+0000 Status: Resolved Fix version(s): - 0.9.3 (05/May/07)
 
 Reporter:  Gauthier Alarcon (golgoth)  Assignee:  Matthew Weier O'Phinney (matthew)  Tags: - Zend\_Controller
 
 Related issues: 
 Attachments: 
### Description

Zend\_Controller\_Front::dispatch() does not render response's exceptions, even if I set response's renderException flag to TRUE.

 
    <pre class="highlight">$response = new Zend_Controller_Response_Http();
    $response->setException(new Exception('My message...'));
    $response->renderExceptions(true);
    
    $front = Zend_Controller_Front::getInstance();
    $front->setResponse($response);
    ...
    $front->dispatch();

At the end of dispatch the front controller sends response with sendHeaders() and outputBody() methods, but response object renders exceptions only through sendResponse() method.

I don't understand why front controller sends response this way, a call to sendResponse() or a simple echo should do the work. I think the response object should decide alone how to handle exceptions.

 

 

### Comments

Posted by Bill Karwin (bkarwin) on 2007-04-17T19:19:54.000+0000

Assign to Matthew.

 

 

Posted by Matthew Weier O'Phinney (matthew) on 2007-05-04T15:18:11.000+0000

Resolved in r4716

 

 