---
layout: issue
title: "Code which tests for an exception throw should be modified in some cases"
id: ZF-3802
---

ZF-3802: Code which tests for an exception throw should be modified in some cases
---------------------------------------------------------------------------------

 Issue Type: Unit Tests: Task Created: 2008-07-29T11:43:45.000+0000 Last Updated: 2011-02-18T14:34:46.000+0000 Status: Postponed Fix version(s): 
 Reporter:  Alexander Veremyev (alexander)  Assignee:  Alexander Veremyev (alexander)  Tags: 
 Related issues: 
 Attachments: 
### Description

There are a lot of tests which use constructions similar to this:

 
    <pre class="highlight">
    try {
    ...
        // Some code which must throw an exception
    
        $this->fail('Some message');
    } catch (Exception $e) {
        // Success
        // Do nothing
    }


It doesn't work. PHPUnit fail() tests flow management is also exception based. So test failure (if it appears) is not registered since fail exception is caught.

In most cases only component specific exceptions (or Zend\_Exception) should be caught. But we should be accurate enough with just replacing Exception to Zend\_Exception through whole ZF tests code.

Searching for '(Exception' through ZF tests code returns 97 files

 

 

### Comments

Posted by Thomas Weidner (thomas) on 2008-07-29T12:00:20.000+0000

It's ok when an component-specific exception is catched... something like

 
    <pre class="highlight">
    try {
      $this->assertEquals(..., ...);
      $this->fail('failed');
    } catch (Zend_Db_Exception $e) {
      // failed, run through
    }


But it's always better to test also for the exception text which is really easy...

 
    <pre class="highlight">
    try {
      $this->assertEquals(..., ...);
      $this->fail('failed');
    } catch (Zend_Db_Exception $e) {
      $this->assertContains('my exception text', $e->getMessage());
    }


This is the proper way of testing exceptions and should be done in all ZF testbeds. Btw: Just searching for "Exception" is not enough, because Zend\_Exception or Zend\_Db\_Exception will also return "Exception".

To clearify... just replacing Exception with Zend\_Exception is not enough for proper testing.

Greetings Thomas, I18N Team Leader

 

 

Posted by Alexander Veremyev (alexander) on 2008-07-29T12:28:07.000+0000

Yeah.

There is also another way to test for expected exceptions mentioned by Matthew:

 
    <pre class="highlight">
    /**
     * @expectedException Zend_Foo_Exception
     */
    public function testSuchAndSuchShouldThrowExceptionWithInvalidInput()
    {
        // ...
    }


 

 

Posted by julien PAULI (doctorrock83) on 2008-07-30T03:58:28.000+0000

Yes Alex, it's the same as $this->setExpectedException().

 

 