---
layout: issue
title: "Fatel Error"
id: ZF-4189
---

ZF-4189: Fatel Error 
---------------------

 Issue Type: Bug Created: 2008-09-04T11:03:05.000+0000 Last Updated: 2008-09-10T11:42:35.000+0000 Status: Resolved Fix version(s): 
 Reporter:  harsha udayanga (devhash)  Assignee:  Matthew Weier O'Phinney (matthew)  Tags: - Zend\_Controller
 
 Related issues: 
 Attachments: 
### Description

Fatal error: Uncaught exception 'Zend\_Controller\_Action\_Exception' with message 'Action "placecredithold" does not exist and was not trapped in \_\_call()' in /usr/local/Zend/Core/share/ZendFramework-1.5.2/library/Zend/Controller/Action.php:477 Stack trace: #0 /usr/local/Zend/Core/share/ZendFramework-1.5.2/library/Zend/Controller/Action.php(504): Zend\_Controller\_Action->\_\_call('placecredithold...', Array) #1 /usr/local/Zend/Core/share/ZendFramework-1.5.2/library/Zend/Controller/Dispatcher/Standard.php(293): Zend\_Controller\_Action->dispatch('placecredithold...') #2 /usr/local/Zend/Core/share/ZendFramework-1.5.2/library/Zend/Controller/Front.php(914): Zend\_Controller\_Dispatcher\_Standard->dispatch(Object(Zend\_Controller\_Request\_Http), Object(Zend\_Controller\_Response\_Http)) #3 /var/www/int/class/Hb/Util/Control/Front.class(65): Zend\_Controller\_Front->dispatch() #4 /var/www/int/app/index.php(9): Hb\_Util\_Control\_Front::run() #5 {main} thrown in /usr/local/Zend/Core/share/ZendFramework-1.5.2/library/Zend/Controller/Action.php on line 477

 

 

### Comments

Posted by Matthew Weier O'Phinney (matthew) on 2008-09-04T11:42:47.000+0000

Please provide the controller class that should contain the action.

My assumption is that you have an action entitled placeCreditHoldAction() and that you're trying to access it with a url that includes the string 'placeCreditHold' instead of 'place-credit-hold'. If so, please read the Migration section of the Zend\_Controller manual.

 

 

Posted by Matthew Weier O'Phinney (matthew) on 2008-09-10T11:42:35.000+0000

Closing due to lack of feedback.

 

 