---
layout: issue
title: "Allow MVC dispatch to perform shutdown even after exception"
id: ZF-545
---

ZF-545: Allow MVC dispatch to perform shutdown even after exception
-------------------------------------------------------------------

 Issue Type: Improvement Created: 2006-11-11T23:18:55.000+0000 Last Updated: 2007-07-05T14:43:28.000+0000 Status: Resolved Fix version(s): - 0.6.0 (16/Dec/06)
 
 Reporter:  Simon Mundy (peptolab)  Assignee:  Matthew Weier O'Phinney (matthew)  Tags: - Zend\_Controller
 
 Related issues: 
 Attachments: 
### Description

in the Front Controller if any portion of the dispatch process throws an exception, it's caught and added to the response in lines 541-543. Unfortunately, though, it means that any 'cleanup' plugins that utilise 'dispatchLoopShutdown' are missed. Would it cause any grief if the shutdown sequence is called after the 'catch', so it's called in any event regardless of error?

 

 

### Comments

Posted by Bill Karwin (bkarwin) on 2006-11-13T14:57:00.000+0000

Assigning to Matthew.

 

 

Posted by Bill Karwin (bkarwin) on 2006-11-13T15:24:58.000+0000

Changing fix version to 0.6.0.

 

 

Posted by Matthew Weier O'Phinney (matthew) on 2006-11-22T21:47:37.000+0000

Resolved in revision 1836

 

 