---
layout: issue
title: "throw exceptions within foreach is now available"
id: ZF-583
---

ZF-583: throw exceptions within foreach is now available
--------------------------------------------------------

 Issue Type: Patch Created: 2006-11-22T03:08:05.000+0000 Last Updated: 2010-02-10T12:07:46.000+0000 Status: Closed Fix version(s): 
 Reporter:  Aleksey V. Zapparov (ixti)  Assignee:  Gavin (gavin)  Tags: - Zend\_Loader
 
 Related issues: 
 Attachments: 
### Description

 
    <pre class="highlight">
    $e = '';
    // an object can only be stored in the registry once
    foreach (self::$_registry as $dup=>$registeredObject) {
        if ($obj === $registeredObject) {
            $e = "Duplicate object handle already exists in the registry as \"$dup\".";
            break;
        }
    }
    
    /**
     * @todo throwing exceptions inside foreach could cause leaks, use a workaround
     *       like this until a fix is available
     *
     * @link <a href="http://bugs.php.net/bug.php?id=34065">http://bugs.php.net/bug.php?id=34065</a>
     */
    if ($e) {
        throw new Zend_Exception($e);
    }


now it can be

 
    <pre class="highlight">
    // an object can only be stored in the registry once
    foreach (self::$_registry as $dup=>$registeredObject) {
        if ($obj === $registeredObject) {
            throw new Zend_Exception("Duplicate object handle already exists in the registry as \"$dup\".");
        }
    }


But if ZF's minimal requirements will be PHP 5.2.0 (foreach memleak fixed in it).

 

 

### Comments

Posted by Bill Karwin (bkarwin) on 2006-12-01T18:52:01.000+0000

Assigning to Gavin.

 

 

Posted by Gavin (gavin) on 2006-12-18T12:53:39.000+0000

Fixed in changeset 2387.

 

 