---
layout: issue
title: "change exception message raised in Zend_Log::__call() to not be context sensitive."
id: ZF-5884
---

ZF-5884: change exception message raised in Zend\_Log::\_\_call() to not be context sensitive.
----------------------------------------------------------------------------------------------

 Issue Type: Improvement Created: 2009-02-25T13:12:08.000+0000 Last Updated: 2011-01-20T11:47:59.000+0000 Status: Open Fix version(s): 
 Reporter:  Chance Garcia (chance)  Assignee:  Eddo Rotman (karnaf)  Tags: - Zend\_Log
 
 Related issues: 
 Attachments: 
### Description

right now the exception message shown is "Bad log priority".

But that may not be the actual reason for the error. Suppose in my code I have

$log->addEventItem('foo','bar');

This would throw the "Bad log priority" exception message since \_\_call() is overridden to provide a convenience method for doing $log->priorityName('message'); instead of $log->log('message', Zend\_Log::PRIORITY\_NAME);

the current exception message thrown isn't helpful because it is context sensitive. A more useful message would be "\_\_call() is unable to trap the method $method" or something to that effect.

 

 

### Comments

Posted by Thomas Weidner (thomas) on 2010-03-21T10:26:39.000+0000

Reassigned to component maintainer

 

 

Posted by Beno√Æt Durand (intiilapa) on 2011-01-20T11:47:58.000+0000

The magic call method should be used only in order to log an event with a quick friendly syntax. How to do you want distinct a bad log priority of an undefined method?

 

 