---
layout: issue
title: "change behaviour of isValid to no longer throw exceptins, but return generic error instead"
id: ZF-9895
---

ZF-9895: change behaviour of isValid to no longer throw exceptins, but return generic error instead
---------------------------------------------------------------------------------------------------

 Issue Type: New Feature Created: 2010-05-26T14:16:06.000+0000 Last Updated: 2010-08-12T07:15:32.000+0000 Status: Resolved Fix version(s): 
 Reporter:  Ryan Mauger (bittarman)  Assignee:  Ryan Mauger (bittarman)  Tags: - Zend\_Validate
 
 Related issues: 
 Attachments: 
### Description

the isValid method for validators should not thow exceptions, only return true, or false.

As such, the behaviour needs to be changed, to catch the exception, and return false, with a generic error set.

 

 

### Comments

Posted by Matthew Weier O'Phinney (matthew) on 2010-05-27T04:04:35.000+0000

Most validators do not throw exceptions anyways. The ones that do do so in exceptional circumstances -- missing DB connection, invalid query, etc. I think in these situations, a simple "false" return value would be quite a bad idea, as it could return a false negative, which is a potentially worse situation.

Can you give some examples of where you would want this changed?

 

 

Posted by Thomas Weidner (thomas) on 2010-05-27T12:03:53.000+0000

Actually no validator throws exceptions. The idea is that isValid() only returns boolean and you don't need to cover all isValid calls with an catch statement. This was a real pain before 1.5.

When I have a DB validator I can easily check the DB connection when I create the object. No need to throw an exception as this check is done before.

When I attach a query there is no need to throw an exception... I could eighter check the query when I attach it and I could also return an false with the proper error-text. This is already done in several other validators.

Generally the idea is that all things which can throw an exception, should be checked before calling isValid() so no exception has to be thrown. In past this way was accepted and I changed all validators to behave this way. I remember that we had this discussion already about 1 year ago.

 

 

Posted by Ryan Mauger (bittarman) on 2010-05-27T12:16:13.000+0000

There is actually another good reason for swallowing the exception, and producing a generic error fail case.

There are some circumstances, such as an overloaded db server, where everything can be done correctly, yet the query still fail.

Because of this, with the current nature of how DB exceptions are handled, it is impossible to selectively look for individual types of exception, to identify which ones are actually developer fault, and which are simply exceptional circumstance.

Because we cannot reliably check the type of exception raised, it would be incorrect to allow the exception to be raised, as under most circumstances, the developer would probably wish to simply allow the user to try again, rather than switching to a 501 page. This behavior change allows for this. With this consideration in place, I feel that a method to log the exception should be provided, so that debugging is much easier. To this end, I am of the mind that adding isException, and getException methods to allow the developer to test for, extract, and log the exception would be the most suitable case, and where other validators also swallow exceptions to the same end, perhaps this should be made consistent across the entire Zend\_Validate namespace.

 

 

Posted by Jurrien Stutterheim (norm2782) on 2010-05-28T03:57:34.000+0000

Trying to summarize a discussion we just had on IRC. The way I see it:

- A validator should only return a boolean value
- Unless an exception is thrown, for example, by a database operation. In that case, the exception should bubble up to user code can be caught there. It is an exceptional state of the program after all. There is no more need for the result of the validation, as it won't ever return the representative boolean value; the actual validation never occurred.
- Implication of this is that, yes, you do need try/catch blocks around isValid() calls that can potentially throw exceptions. There is no need to try and hide perfectly normal language behavior and constructs.
- Hiding exceptions by silently discarding them in the background is unwanted. It makes debugging and graceful error handling significantly harder, and it negates the role that exceptions play in the first place.
- Separation of concerns needs to be kept in mind. Validators should validate, database connections should try and make connections to a database, try/catch blocks should catch exceptions, and logging facilities should log exceptions. Don't try to put this all in the validator.
 


 

Posted by Christian Albrecht (alab) on 2010-05-30T16:17:46.000+0000

Although I am able to see the benefits for Form Validation and User Experience, I am against adding more responsibilities to Zend\_Form. Especially since a goal for Zend\_Form-2.0 is to separate concerns and decouple Zend\_Validate from it.

Imho, it would be better to create a Zend\_Db\_ExceptionLogger Interface and Class which when activated prevents throwing Exceptions - instead logs them, and make Zend\_Db return appropriate null|false values.

 

 

Posted by Christian Albrecht (alab) on 2010-05-31T01:09:59.000+0000

Duhh, forget my last sentence in the previous comment, that would not give a meaningful Error Message to the user, I figured.

 

 

Posted by Ryan Mauger (bittarman) on 2010-08-12T07:15:31.000+0000

Largely decided that this should not be the case after much debate on IRC.

 

 